### ISSUE TITLE
Color modify in tailwindcss.config.js not applied

### ISSUE THREAD

**Issue by TrungRueta** [windicss/vue-cli-plugin-windicss#2]
Hi!

I would like to report a bug. I followed instruction and setup success plugin to vue-cli v4. Everything seem working perfect with default, but when i try to modify color pallette site not apply new color, but from `Windi css: analysis` command (windicss vscode extension) i saw color reported as changed. 

Look like vscode's extension compile correct, but vue-cli plugin compile not correct.

This is my tailwind.config.js:

```js
const colors = require('windicss/colors');

module.exports = {
  important: true,
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {
      container: {
        center: true,
        padding: '1.5rem',
      },
      screens: {
        // add media print screen
        print: { raw: 'print' },
      },
      colors: {
        cyan: colors.cyan,
        primary: colors.emerald,
        green: colors.emerald,
        gray: colors.blueGray,
      },
    },
  },
  variants: {
    extend: {
      display: ['group-hover'],
      visibility: ['group-hover'],
      borderWidth: ['first', 'last'],
      borderRadius: ['first', 'last'],
    },
  },
};
```

Colors:  `primary` show purple, not emerald. `gray`show default, not cool gray etc.

---

Update: After spend a hour testing and play with config. i found we have some issue:

1. In README i saw we have meantion: 
`If you have a tailwind.config.js, please rename it to windi.config.js or windi.config.ts.`. This message is important, but stay in small position and hard to catch by eyes. 
2. Although had meantion about "must use filename `windi.config.{js|ts}` but actually i still can leave filename `tailwind.config.{js|ts}` and add one more property `config: "..."` in `vue.config.js` like this:
```js
pluginOptions: {
    windicss: {
      // see https://github.com/windicss/vite-plugin-windicss/blob/main/packages/plugin-utils/src/options.ts
      scan: {
        dirs: ['./src'],
        exclude: [
          'node_modules',
          '.git',
          'public/**/*',
          '*.template.html',
          'index.html',
          'dist',
        ],
        include: [],
      },
      transformCSS: 'pre',
      compile: false,
      config: 'tailwind.config.js' // <- here , copy from config of other windicss plugin
    },
  },
```
Plugin will working normally, no throwing any warning and error, but look like content not be read and lead to issue i reported above (about color not applied).

3. If i leave property `config: "..."` in `vue.config.js` and change filename `tailwind.config.*` to `windi.config.*` when running vue-cli i will get mesasge not found config file.
4. if i remove `config: "..."` and change filename to `windi.config.*` then everything work perfect. Config file applied. 

So... I think i found workaround, but it still be a bug. Hope my explains help plugin can be fixed.

Thank you!!

**Comment by harlan-zw** [comment]
Hey @TrungRueta 

Thanks for the detailed issue and sorry you had issues.

I'm glad you found an issue, when I have some times I'll see when changes I can make so other developers don't run into this.
