### ISSUE TITLE
Classes are ignored on index.html file

### ISSUE THREAD

**Issue by julesrx** [windicss/vue-cli-plugin-windicss#22]
Hi,

I'm trying to to add styles to the body on a Vue CLI 4 app, but the classes are ignored by the plugin. The style are not generated.
![image](https://user-images.githubusercontent.com/25800503/116929019-2013bd80-ac5e-11eb-99d0-ee81903ef66b.png)

I tried to force the scanning with the [`extract.include` option](https://windicss.org/guide/extractions.html#scanning) or the pluginOptions, with no effect.

To reproduce :
- `vue create vue-app`
- `vue add windicss`
- add `bg-red-500` to the body
- `npm run serve`

On @vue/cli 4.5.12

----

Edit: 
Seeing the plugin source, i can see that the public folder and `index.html` are ignored by default, [which seems to come from the windi webpack plugin](https://github.com/windicss/windicss-webpack-plugin/blob/HEAD/src/loaders/transform-template.ts#L28) ?

Tried to override it, I had to add my classes to the [`safelist` option](https://windicss.org/guide/extractions.html#safelist).
This is a real downside for me compared to the vite plugin, who directly works with `index.html`.

**Comment by harlan-zw** [comment]
Hey @julesrx 

Thanks for writing up an issue. There was a technical reason why HTML files couldn't be passed, basically a limitation with the html-webpack-plugin, however, I have found a workaround.

Please upgrade to v0.2.0 and let me know if you have any issues.

**Comment by julesrx** [comment]
This works thanks 👍
