### ISSUE TITLE
pnpm install vue-cli-plugin-windicss failed

### ISSUE THREAD

**Issue by cuiliangl** [windicss/vue-cli-plugin-windicss#34]
![image](https://user-images.githubusercontent.com/25759364/146509555-eb39dede-4b20-4864-a183-075c6e08f09e.png)
![image](https://user-images.githubusercontent.com/25759364/146509853-92924259-e441-46fe-ba58-0cc4df6ec4f2.png)

**Comment by nickolboy** [comment]
+1

**Comment by harlan-zw** [comment]
Hey @cuiliangl & @nickolboy 

Can you provide the steps to reproduce? Not sure how to run vue-cli with pnpm

**Comment by cuiliangl** [comment]
>
