### ISSUE TITLE
To get the last version of windi - do I have to wait for a new version of this library?

### ISSUE THREAD

**Issue by Madd0g** [windicss/vue-cli-plugin-windicss#35]
I see the underlying `windicss-webpack-plugin` reference the latest windi, but when I try to upgrade with:

```
vue upgrade
```

or

```
yarn upgrade-interactive --latest
```

and both do not offer to upgrade the `windicss` sub-dependency.

**Comment by harlan-zw** [comment]
Sorry for the delay, dependencies are updated in 1.1.4

**Comment by Madd0g** [comment]
thanks!
