### ISSUE TITLE
use vue-cli-plugin-windicss, the import statement in router is invalid

### ISSUE THREAD

**Issue by hc9527** [windicss/vue-cli-plugin-windicss#38]
https://segmentfault.com/q/1010000042289975

**Comment by harlan-zw** [comment]
Hey, would it be possible to create a reproduction with stackblitz for this?

**Comment by hc9527** [comment]
The package.json in question looks like this
`
"vue-cli-plugin-windicss": "~1.1.6",
"vue": "2.6.14",
"vue-router": "3.1.5",
"typescript": "^4.8.2",
`

**Comment by hc9527** [comment]
I found out it was the eslint problem

**Comment by harlan-zw** [comment]
Glad you found the issue :) Thanks for the update
